version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
     - run:
        name: Running X virtual framebuffer
        command: Xvfb :99 -screen 0 1280x1024x24
        background: true

- run: make test

      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
          
