version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
            
      - run: 
          name: "creating mkdir"
          command: mkdir -p /tmp/test-results
          
      - run:
         name: "Test the executable"
         command: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe

      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "circleci-demo-windows.csproj" }}
          
